tenants:
  # Tenant A Specific Information - VRFs / VLANs
  PROJECT01:
    mac_vrf_vni_base: 10000
    vrfs:
      PRJ01_APP01:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          111:
            name: VLAN_VTEP_01_02
            tags: [rack01]
            enabled: true
            ip_address_virtual: 10.1.11.1/24
          112:
            name: VLAN_VTEP_03_04
            tags: [rack02]
            enabled: true
            ip_address_virtual: 10.1.12.1/24
    l2vlans:
      110:
        vni_override: 55160
        name: L2VLAN_FABRIC
        tags: [compute]
