---
local_users:
  admin:
    privilege: 15
    role: network-admin
    no_password: true
    # sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  ansible:
    privilege: 15
    role: network-admin
    # password: ansible
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

  arista:
    privilege: 15
    role: network-admin
    # password: arista
    sha512_password: "$6$7WhvEi5Ce5f5Ut3z$Ethmha7rb710RKsaVteusVOuNP1Utfjzse58xxbgiZp4MF0fp7BX5lAw8yBgv/HWCihVomuCSrsJx8wKnJ7Tm1"

  tom:
    privilege: 15
    role: network-admin
    # password: arista123
    sha512_password: "$6$TyWn7NeXe/vBRl1t$S4fEOkPmpTGz7TLHCzDNP8D2UfpO3ciC2MuGmCaFMVF3B7zt9KSnt9yq99y69XBIY1HV/kO4QjOk32yRQOru5."

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
# If ATD is running cEOS, management interface is Management0
# If ATD is running vEOS, management interface is Management1
mgmt_interface: Management0
mgmt_interface_vrf: default

daemon_terminattr:
  cvaddrs:
    - 10.73.1.238:9910
  cvauth:
    method: token
    token_file: "/tmp/token"
  cvobscurekeyfile: false
  cvsourceip: '{{ ansible_host }}'
  cvvrf: default
  cvgnmi: true
  disable_aaa: false
  ingestexclude: '/Sysdb/cell/1/agent,/Sysdb/cell/2/agent'
  smashexcludes: 'ale,flexCounter,hardware,kni,pulse,strata'

# dns servers.
name_servers:
  - 192.168.2.1
  - 8.8.8.8

# dns domain
dns_domain: atd.lab

# NTP Servers IP or DNS name, first NTP server will be prefered, and sourced from Managment VRF
# ntp_servers:
#  - 192.168.0.1

aaa_authorization:
  exec:
    default: local
