svi_profiles:
  GENERIC:
    mtu: 1560
    enabled: true
  GENERIC_FULL:
    name: GENERIC Name
    mtu: 1560
    enabled: false
    ip_address_virtual: 10.1.10.254/24
  WITH_NO_MTU:
    enabled: true
  WITH_SNOOPING:
    enabled: true
    igmp_snooping_enabled: false

tenants:
  # Tenant A Specific Information - VRFs / VLANs
  PROJECT01:
    mac_vrf_vni_base: 10000
    vrfs:
      PRJ01_APP01:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          111:
            name: VLAN_VTEP_01_02
            tags: [rack01]
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          112:
            name: VLAN_VTEP_03_04
            tags: [rack02]
            enabled: true
            ip_address_virtual: 10.1.10.1/24
    l2vlans:
      110:
        vni_override: 55160
        name: L2VLAN_FABRIC
        tags: [compute]
  # Tenant_B:
  #   mac_vrf_vni_base: 20000
  #   vrfs:
  #     Tenant_B_OP_Zone:
  #       vrf_vni: 20
  #       svis:
  #         210:
  #           name: Tenant_B_OP_Zone_1
  #           tags: ['opzone']
  #           profile: WITH_NO_MTU
  #           ip_address_virtual: 10.2.10.1/24
  #         211:
  #           name: Tenant_B_OP_Zone_2
  #           tags: ['opzone']
  #           profile: GENERIC_FULL
  #           ip_address_virtual: 10.2.11.1/24