---
ansible_httpapi_host: '{{ ansible_host }}'
ansible_connection: httpapi
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_network_os: eos
ansible_httpapi_port: 443

ansible_password: '{{ ansible_ssh_pass }}'
ansible_become: yes
ansible_become_method: enable