---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: ATD_LAB
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: generate intended variables
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: eos_cli_config_gen

- name: Configuration deployment with CVP
  hosts: ATD_LAB
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: provision EOS devices with AVD configuration
      tags: [deploy]
      import_role:
        name: arista.avd.eos_config_deploy_eapi
